"""empty message

Revision ID: c92d5602e33e
Revises: e4fda7743687
Create Date: 2024-03-19 11:56:21.102870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c92d5602e33e'
down_revision: Union[str, None] = 'e4fda7743687'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('defendant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('process_number', sa.String(), nullable=True),
    sa.Column('action_infraction', sa.String(), nullable=True),
    sa.Column('detail', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_defendant_id'), 'defendant', ['id'], unique=False)
    op.create_table('details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('actors', sa.String(), nullable=True),
    sa.Column('defendants', sa.String(), nullable=True),
    sa.Column('judicial_process', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_details_id'), 'details', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_details_id'), table_name='details')
    op.drop_table('details')
    op.drop_index(op.f('ix_defendant_id'), table_name='defendant')
    op.drop_table('defendant')
    # ### end Alembic commands ###
